name: 'Build'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["colemak"]'
      nav: '["vi"]'
      clipboard: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      kmonad_os: '["default"]'
